env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parser: "@typescript-eslint/parser"
extends: ['plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
  project: "./tsconfig.json"

plugins: ['react']

settings:
  react:
    version: '16'